import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/providers/theme-provider';
import Sidebar from '@/components/sidebar/sidebar';
import { Button } from '@/components/ui/button';
import { TooltipProvider } from '@/components/ui/tooltip';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {' '}
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <TooltipProvider>
            <Sidebar className='fixed bottom-0 top-0 w-60 border-r-[1px] border-border' />
            <main className='pl-60'>
              <section className='p-6 space-y-2'>
                <div className='w-full'>
                  <Button variant='link'>Project</Button>
                  {'>'}
                  <Button variant='link'>Version</Button>
                  {'>'}
                  <Button variant='link'>Board</Button>
                </div>
                {children}
              </section>
            </main>
          </TooltipProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
